[workspace]
resolver = "2"
members = [
    "crates/example-mud",
    "crates/grim",
    "crates/grim-protocol-telnet",
    "crates/grim-client",
    "crates/grim-engine-types",
]

[workspace.dependencies]
bevy = { version = "0.19", default-features = false, features = ["bevy_log"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
sha2 = "0.10"