[package]
name = "grim-persistence"
version = "0.1.0"
edition = "2021"

[dependencies]
grim-engine-types = { path = "../grim-engine-types" }
grim-networking = { path = "../grim-networking" }
bevy = { workspace = true, default-features = false }
serde_json = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
chrono = { workspace = true }
