[package]
name = "grim"
version = "0.1.0"
edition = "2021"

[dependencies]
grim-engine-types = { path = "../grim-engine-types" }
grim-text = { path = "../grim-text" }
grim-command = { path = "../grim-command" }
grim-networking = { path = "../grim-networking" }
grim-networking-telnet = { path = "../grim-networking-telnet" }
grim-scene = { path = "../grim-scene" }
grim-world = { path = "../grim-world" }
grim-channel = { path = "../grim-channel" }
grim-persistence = { path = "../grim-persistence" }
bevy = { workspace = true, default-features = false }
